### ISSUE TITLE
Framed Drawer Controller showing <ERROR> in HWYLA

### ISSUE THREAD

**Issue by overchoice** [eutropius225/FramedCompactDrawers#1]
Hi. The framed controller is working as intended but is showing an error for the tooltip.

![2020-04-17_07 53 21](https://user-images.githubusercontent.com/50001839/79572199-24d0f800-8082-11ea-9f07-5291e61b9a53.png)

![2020-04-17_07 54 09](https://user-images.githubusercontent.com/50001839/79572209-28fd1580-8082-11ea-8954-4f004916810b.png)

**Comment by eutropius225** [comment]
Fixed in e74ac42.
